const Menu = [
    {
        id: 1,
        image: "Images/maggi.jpg",
        name: "Maggi",
        category: "Breakfast",
        price: "100/-",
        description:" I love Maggi We believe that by   focusing on natural ingredients.",
    },
    {
        id: 2,
        image: "Images/bolidegg.jpg",
        name: "Boiled Eggs",
        category: "Breakfast",
        price: "50/-",
        description:" I love Bolid egg cooks plan,reducing salt and focusing on natural ingredients.",
    },
    {
        id: 3,
        image: "Images/breadjam.jpg",
        name: "Bread Jam",
        category: "Breakfast",
        price: "30/-",
        description:" I love Bread with Jam  we can all contribute to a better tomorrow.",
    },
    {
        id: 4,
        image: "Images/chaibunmakkhan.jpg",
        name: "Chai Bun-Makkhan",
        category: "Breakfast",
        price: "25/-",
        description:" I love Chai with Bun-Makkhan  we can all contribute to a better tomorrow.",
    },
    {
        id: 5,
        image: "Images/cholebhature.jpg",
        name: "Chole Bhature",
        category: "Lunch",
        price: "100/-",
        description:" I love chole Bhature .",
    },
    {
        id: 6,
        image: "Images/dalmakanirice.jpg",
        name: "Dal Makhani-Jeera Rice ",
        category: "Lunch",
        price: "150/-",
        description:" I love Dal Makhani with jeera rice We believe choices aroun better tomorrow.",
    },
    {
        id: 7,
        image: "Images/kadhirice.jpg",
        name: "Kadhi Chawal",
        category: "Lunch",
        price: "70/-",
        description:" I love Kadhi Chawal We believe that by empowering better daily choices around food, we can all contribute to a better tomorrow.",
    },
    {
        id: 8,
        image: "Images/rajmarice.jpg",
        name: "Rajma Chawal",
        category: "Lunch",
        price: "70/-",
        description:" I love Rajma Chawal We believe that by empowering better daily choices around food, we can all contribute to a better tomorrow.",
    },
    {
        id: 9,
        image: "Images/Lassi.jpg",
        name: "Lassi",
        category: "Lunch",
        price: "50/-",
        description:" I love Lassi We believe that by empowering better daily choices around food.",
    },
    {
        id: 10,
        image: "Images/papdichaat.jpg",
        name: "Papdi Chaat",
        category: "Evening",
        price: "50/-",
        description:" I love Papdi Chaat We believe that by empowering better daily choices .",
    },
    {
        id: 11,
        image: "Images/pizza.jpg",
        name: "Pizza",
        category: "Evening",
        price: "300/-",
        description:" I love Pizza We believe that by empowering better daily choices around food.",
    },
    {
        id: 12,
        image: "Images/khasta.jpg",
        name: "Khasta Chaat",
        category: "Evening",
        price: "40/-",
        description:" I love Khasta We believe that by empowering better daily choices around food.",
    },
    {
        id: 13,
        image: "Images/moms.jpg",
        name: "Momos",
        category: "Evening",
        price: "100/-",
        description:" I love Momos  We believe that by empowering better daily choices around food.",
    },
    {
        id: 14,
        image: "Images/aloopakoda.jpg",
        name: "potato Fritters",
        category: "Evening",
        price: "50/-",
        description:" I love Potato Fritters with chutney nutritional value of products too, reducing salt and focusing on natural ingredients.",
    },
    {
        id: 15,
        image: "Images/batashe.jpg",
        name: "Batashe",
        category: "Evening",
        price: "50/-",
        description:" I love Golgappa crispy fried puffed ball filled with chickpeas and favored water.",
    },
    {
        id: 16,
        image: "Images/chickennug.jpg",
        name: "Chicken Nuggets",
        category: "Evening",
        price: "300/-",
        description:" I love Chicken Nuggets We believe that by empowering better daily choices around food, we can all  and focusing on natural ingredients.",
    },
    {
        id: 17,
        image: "Images/samosa.jpg",
        name: "Samosas",
        category: "Evening",
        price: "30/-",
        description:" I love Samosa We believe that by empowering ingredients.",
    },
    {
        id: 18,
        image: "Images/alooparatha.jpg",
        name: "Aloo Paratha",
        category: "Dinner",
        price: "50/-",
        description: " I love Aloo Paratha it is filled with Smashed Potatos with lots of spices. ",
    },
    {
        id: 19,
        image: "Images/eggcurry.jpg",
        name: "Egg curry",
        category: "Dinner",
        price: "200/-",
        description: " I love Egg Curry ",
    },
    {
        id: 20,
        image: "Images/Shahipaneer.jpg",
        name: "Shahi Paneer",
        category: "Dinner",
        price: "200/-",
        description:" I love Shahi Paneer We believe that  continuously working on improving the nutritional value of products too, reducing salt and focusing on natural ingredients.",
    },
    {
        id: 21,
        image: "Images/tandorichicken.jpg",
        name: "Tandori Chicken ",
        category: "Dinner",
        price: "300/-",
        description:" I love Tandori Chicken on natural ingredients.",
    },
    {
        id: 22,
        image: "Images/plainroti.jpg",
        name: "Plain roti",
        category: "Dinner",
        price: "10/-",
        description: " I love Plain roti We believe that by empowering better daily choices around food, "
    },
    {
        id: 23,
        image: "Images/rumaliroti.jpg",
        name: "Rumali Roti",
        category: "Dinner",
        price: "10/-",
        description:" I love Rumali Roti We believe that by empowering better daily choices around food.",
    },
    {
        id: 24,
        image: "Images/butternaan.jpg",
        name: "Butter Naan",
        category: "Dinner",
        price: "30/-",
        description:" I love Butter Naan We  and  value of products too, reducing salt and focusing on natural ingredients.",
    },
    {
        id: 25,
        image: "Images/icecream.jpg",
        name: "Ice Creams",
        category: "Dessert",
        price: "100/-",
        description:" I am fond of Ice creams  working on improving the nutritional value of products too, reducing salt and focusing on natural ingredients.",
    },
    {
        id: 26,
        image: "Images/blackforestp.jpg",
        name: "Black Forest Pastry",
        category: "Dessert",
        price: "90/-",
        description:" I love Black Forest Pastry We believe that  encourage  focusing on natural ingredients.",
    },
    {
        id: 27,
        image: "Images/gulabjamun.jpg",
        name: "Gulab Jamun",
        category: "Dessert",
        price: "50/-",
        description: " I love Gulab Jamun We believe that by  focusing on natural ingredients.",
    },
    {
        id: 28,
        image: "Images/redvelvet.jpg",
        name: "Red Velvet Pastry",
        category: "Dessert",
        price: "100/-",
        description:" I love Red Velvet Pastry We believe that by continuously working on focusing on natural ingredients.",
    },
];
export default Menu;